/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardFiltersRouteImport } from './routes/dashboard/filters'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardBackendsRouteImport } from './routes/dashboard/backends'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as AuthAuthViewRouteImport } from './routes/auth/$authView'
import { Route as AdminOverviewRouteImport } from './routes/admin/overview'
import { Route as AdminOrganizationsRouteImport } from './routes/admin/organizations'
import { Route as AdminBlacklistsRouteImport } from './routes/admin/blacklists'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFiltersRoute = DashboardFiltersRouteImport.update({
  id: '/filters',
  path: '/filters',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBackendsRoute = DashboardBackendsRouteImport.update({
  id: '/backends',
  path: '/backends',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthAuthViewRoute = AuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/admin/overview',
  path: '/admin/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/admin/organizations',
  path: '/admin/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlacklistsRoute = AdminBlacklistsRouteImport.update({
  id: '/admin/blacklists',
  path: '/admin/blacklists',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/admin/blacklists': typeof AdminBlacklistsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/backends': typeof DashboardBackendsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/filters': typeof DashboardFiltersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/blacklists': typeof AdminBlacklistsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/backends': typeof DashboardBackendsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/filters': typeof DashboardFiltersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/admin/blacklists': typeof AdminBlacklistsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/backends': typeof DashboardBackendsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/filters': typeof DashboardFiltersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/admin/blacklists'
    | '/admin/organizations'
    | '/admin/overview'
    | '/auth/$authView'
    | '/dashboard/analytics'
    | '/dashboard/backends'
    | '/dashboard/billing'
    | '/dashboard/filters'
    | '/dashboard/settings'
    | '/admin'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/blacklists'
    | '/admin/organizations'
    | '/admin/overview'
    | '/auth/$authView'
    | '/dashboard/analytics'
    | '/dashboard/backends'
    | '/dashboard/billing'
    | '/dashboard/filters'
    | '/dashboard/settings'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/admin/blacklists'
    | '/admin/organizations'
    | '/admin/overview'
    | '/auth/$authView'
    | '/dashboard/analytics'
    | '/dashboard/backends'
    | '/dashboard/billing'
    | '/dashboard/filters'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AdminBlacklistsRoute: typeof AdminBlacklistsRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AuthAuthViewRoute: typeof AuthAuthViewRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/filters': {
      id: '/dashboard/filters'
      path: '/filters'
      fullPath: '/dashboard/filters'
      preLoaderRoute: typeof DashboardFiltersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/backends': {
      id: '/dashboard/backends'
      path: '/backends'
      fullPath: '/dashboard/backends'
      preLoaderRoute: typeof DashboardBackendsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/$authView': {
      id: '/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof AuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/admin/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/admin/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blacklists': {
      id: '/admin/blacklists'
      path: '/admin/blacklists'
      fullPath: '/admin/blacklists'
      preLoaderRoute: typeof AdminBlacklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBackendsRoute: typeof DashboardBackendsRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardFiltersRoute: typeof DashboardFiltersRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBackendsRoute: DashboardBackendsRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardFiltersRoute: DashboardFiltersRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AdminBlacklistsRoute: AdminBlacklistsRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AuthAuthViewRoute: AuthAuthViewRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
